### ISSUE TITLE
Training error - RuntimeError: The size of tensor a (128) must match the size of tensor b (160)

### ISSUE THREAD

**Issue by erezposner** [nadeemlab/CEP#10]
Hi, Following your instructions I am trying to train CLTS-GAN on the public dataset [oldIt_public_data](https://zenodo.org/record/5519974#.Y2Zg_9JBzJU).

My input arguments are as follows:
```
--dataroot ./Data/cep/FoldIt_public --model cltsgan --name "cltsgan_model_name"
```
I get the following error
```
Traceback (most recent call last):
  File "/snap/pycharm-professional/306/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/306/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/eposner/Repositories/CEP/train.py", line 51, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/home/eposner/Repositories/CEP/models/cltsgan_model.py", line 262, in optimize_parameters
    self.forward()      # compute fake images and reconstruction images.
  File "/home/eposner/Repositories/CEP/models/cltsgan_model.py", line 136, in forward
    self.rec_A   = self.netG_B(self.fake_B, self.nfake_B, self.tfake_B)   # G_B(G_A(A))
  File "/home/eposner/anaconda3/envs/CEP/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eposner/Repositories/CEP/models/networks.py", line 619, in forward
    out = out + self.n_parm[i] * n
RuntimeError: The size of tensor a (128) must match the size of tensor b (160) at non-singleton dimension 1
```

I found out the setting --ngf 80 solves this (just like in the googlecolab notebook).
Consider setting it a default value for the dataset?

**Comment by shmathew511** [comment]
Thank you for the suggestion. The default value has been updated.
